# Generated by Django 5.1.15 on 2026-08-08 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('html_body', models.TextField(help_text='Full HTML. Placeholders: {{email}} {{name}} {{lifetime_url}} {{billing_url}} {{unsubscribe_url}} {{price}}')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (not sending)'), ('SENDING', 'Sending'), ('PAUSED', 'Paused'), ('DONE', 'Finished')], default='DRAFT', max_length=8)),
                ('daily_cap', models.PositiveIntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=8)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_emails', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.emailcampaign')),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_1a8cf7_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user'), name='uniq_campaign_recipient')],
            },
        ),
    ]
