# Generated by Django 5.1.15 on 2026-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='auto_enroll',
            field=models.BooleanField(default=False, help_text='Automatically queue every eligible user, including future signups. The weekly per-user cooldown and daily cap still apply.'),
        ),
    ]
