# Generated by Django 5.1.15 on 2026-06-19 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('strategy_focus', models.TextField(blank=True, default='')),
                ('strategy_type', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('NEUTRAL', 'Neutral')], max_length=8)),
                ('confidence_pct', models.PositiveSmallIntegerField()),
                ('timeframe', models.CharField(max_length=8)),
                ('generated_at', models.DateTimeField(db_index=True)),
                ('entry_price', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('tp1', models.FloatField()),
                ('tp2', models.FloatField()),
                ('tp3', models.FloatField()),
                ('tp4', models.FloatField()),
                ('risk_pct', models.FloatField()),
                ('reward_tp1_pct', models.FloatField()),
                ('reward_tp2_pct', models.FloatField()),
                ('reward_tp3_pct', models.FloatField()),
                ('reward_tp4_pct', models.FloatField()),
                ('risk_reward_tp1', models.FloatField()),
                ('risk_reward_tp2', models.FloatField()),
                ('risk_reward_tp3', models.FloatField()),
                ('risk_reward_tp4', models.FloatField()),
                ('dollar_risk', models.FloatField()),
                ('dollar_tp1', models.FloatField()),
                ('dollar_tp2', models.FloatField()),
                ('dollar_tp3', models.FloatField()),
                ('dollar_tp4', models.FloatField()),
                ('reasoning', models.TextField(blank=True, default='')),
                ('invalidation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='market_data.symbol')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='signals.signalservice')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSignalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='signals.signalservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='signals.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'delivered_at'], name='signals_sig_user_id_25c618_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'signal'), name='uniq_user_signal_delivery')],
            },
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['service', '-generated_at'], name='signals_sig_service_45c872_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersignalsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='uniq_user_service'),
        ),
    ]
