# Generated by Django 5.1.15 on 2026-06-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='mae_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='mfe_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='outcome',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TP1', 'Hit TP1'), ('TP2', 'Hit TP2'), ('TP3', 'Hit TP3'), ('TP4', 'Hit TP4'), ('SL', 'Stopped out'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=8),
        ),
        migrations.AddField(
            model_name='signal',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
