# Generated by Django 5.1.15 on 2026-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_signal_mae_pct_signal_mfe_pct_signal_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='outcome',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TP1', 'Hit TP1'), ('TP2', 'Hit TP2'), ('TP3', 'Hit TP3'), ('TP4', 'Hit TP4'), ('SL', 'Stopped out'), ('EXPIRED', 'Expired'), ('INVALID', 'Invalidated (trend changed)')], db_index=True, default='PENDING', max_length=8),
        ),
    ]
