# Generated by Django 5.1.15 on 2026-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_telegramdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramdelivery',
            name='closure_notified',
            field=models.BooleanField(default=False),
        ),
    ]
