# Generated by Django 5.1.15 on 2026-06-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_alter_signal_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='dollar_tp4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='reward_tp4_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='risk_reward_tp4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='tp4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
