# Generated by Django 5.1.15 on 2026-08-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0012_signal_confluence_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalservice',
            name='markets',
            field=models.CharField(choices=[('both', 'Crypto + Forex'), ('crypto', 'Crypto only'), ('forex', 'Forex only')], default='both', help_text='Which asset classes this strategy is scanned on.', max_length=8),
        ),
    ]
