# Generated by Django 5.1.15 on 2026-08-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0013_signalservice_markets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalservice',
            name='markets',
        ),
    ]
