# Generated by Django 5.1.15 on 2026-10-04 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0015_webpushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('code_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='signals.signalservice')),
            ],
            options={
                'ordering': ['service', '-number'],
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='strategy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='signals', to='signals.strategyversion'),
        ),
        migrations.AddConstraint(
            model_name='strategyversion',
            constraint=models.UniqueConstraint(fields=('service', 'number'), name='uniq_service_version_number'),
        ),
        migrations.AddConstraint(
            model_name='strategyversion',
            constraint=models.UniqueConstraint(fields=('service', 'fingerprint'), name='uniq_service_version_fingerprint'),
        ),
    ]
