# Generated by Django 5.1.15 on 2026-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='bybit_symbol',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
