# Generated by Django 5.1.15 on 2026-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_symbol_bybit_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='asset_class',
            field=models.CharField(choices=[('crypto', 'Crypto'), ('forex', 'Forex')], default='crypto', max_length=8),
        ),
        migrations.AddField(
            model_name='symbol',
            name='feed_symbol',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
