# Generated by Django 5.1.15 on 2026-06-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_symbol_asset_class_symbol_feed_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='bybit_symbol',
        ),
    ]
