# Generated by Django 5.1.15 on 2026-06-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0004_remove_symbol_bybit_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='min_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', max_length=16),
        ),
    ]
