# Generated by Django 5.1.15 on 2026-09-11 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_symbol_signals_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('open_interest', models.FloatField(blank=True, null=True)),
                ('funding', models.FloatField(blank=True, null=True)),
                ('mark_px', models.FloatField(blank=True, null=True)),
                ('day_ntl_vlm', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='market_data.symbol')),
            ],
            options={
                'ordering': ['-bucket'],
                'indexes': [models.Index(fields=['symbol', '-bucket'], name='market_data_symbol__c8c59f_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'bucket'), name='uniq_symbol_ctx_bucket')],
            },
        ),
    ]
