# Generated by Django 5.1.15 on 2026-06-20 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('above', 'Crosses above'), ('below', 'Crosses below')], max_length=8)),
                ('target_price', models.FloatField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_price', models.FloatField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='market_data.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='alerts_pric_user_id_f78292_idx')],
            },
        ),
    ]
