# Generated by Django 5.1.15 on 2026-07-26 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0011_signal_daily_ema200_aligned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('bybit', 'Bybit')], default='bybit', max_length=16)),
                ('api_key_enc', models.TextField(blank=True, default='')),
                ('api_secret_enc', models.TextField(blank=True, default='')),
                ('testnet', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=False)),
                ('margin_per_trade_usd', models.FloatField(default=1.0)),
                ('max_open_positions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_daily_trades', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_leverage', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bybit_symbol', models.CharField(max_length=32)),
                ('direction', models.CharField(max_length=8)),
                ('timeframe', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('liquidated', 'Liquidated'), ('skipped', 'Skipped'), ('rejected', 'Rejected')], db_index=True, default='skipped', max_length=12)),
                ('leverage', models.PositiveSmallIntegerField(default=0)),
                ('qty', models.FloatField(default=0.0)),
                ('notional', models.FloatField(default=0.0)),
                ('margin', models.FloatField(default=0.0)),
                ('entry_price', models.FloatField(default=0.0)),
                ('stop_loss', models.FloatField(default=0.0)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('liq_price', models.FloatField(default=0.0)),
                ('order_link_id', models.CharField(blank=True, default='', max_length=64)),
                ('bybit_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('realized_pnl', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='signals.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='execution_t_user_id_e91fbd_idx'), models.Index(fields=['user', 'created_at'], name='execution_t_user_id_42baa3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('signal__isnull', False)), fields=('user', 'signal'), name='uniq_user_signal_execution'), models.UniqueConstraint(condition=models.Q(('order_link_id', ''), _negated=True), fields=('order_link_id',), name='uniq_order_link_id')],
            },
        ),
    ]
