# Generated by Django 5.1.15 on 2026-07-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecution',
            name='breakeven_moved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='scaleout',
            field=models.BooleanField(default=False),
        ),
    ]
