# Generated by Django 5.1.15 on 2026-09-23 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('asset', models.CharField(choices=[('USDT', 'USDT'), ('BTC', 'BTC'), ('LTC', 'LTC')], max_length=8)),
                ('address', models.CharField(max_length=120)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tx_hash', models.CharField(help_text='Transaction hash / ID the user says they paid with.', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved — plan granted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('payment_ref', models.CharField(blank=True, default='', max_length=120)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_payments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='billing_cry_status_b922c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'tx_hash'), name='uniq_asset_txhash')],
            },
        ),
    ]
