# Generated by Django 5.1.15 on 2026-06-23 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0005_telegramdelivery_closure_notified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('sizing_mode', models.CharField(choices=[('risk_pct', 'Risk % of balance'), ('fixed_usd', 'Fixed USD notional'), ('pct_balance', '% of balance notional')], default='risk_pct', max_length=16)),
                ('risk_pct', models.FloatField(default=1.0)),
                ('fixed_usd', models.FloatField(default=100.0)),
                ('pct_balance', models.FloatField(default=5.0)),
                ('leverage', models.PositiveSmallIntegerField(default=3)),
                ('max_open_positions', models.PositiveSmallIntegerField(default=5)),
                ('max_daily_trades', models.PositiveSmallIntegerField(default=10)),
                ('tp_distribution', models.JSONField(default=list)),
                ('move_sl_to_be_after_tp', models.PositiveSmallIntegerField(default=1)),
                ('max_slippage_pct', models.FloatField(default=0.5)),
                ('max_signal_age_sec', models.PositiveIntegerField(default=600)),
                ('min_confidence', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_trade_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('bybit', 'Bybit')], default='bybit', max_length=16)),
                ('testnet', models.BooleanField(default=True)),
                ('api_key_enc', models.TextField()),
                ('api_secret_enc', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('error', 'Error'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('permission_verified', models.BooleanField(default=False)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('open', 'Open'), ('closed', 'Closed'), ('rejected', 'Rejected by broker'), ('skipped', 'Skipped'), ('error', 'Error')], default='submitted', max_length=12)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('side', models.CharField(blank=True, default='', max_length=4)),
                ('bybit_symbol', models.CharField(blank=True, default='', max_length=32)),
                ('qty', models.FloatField(blank=True, null=True)),
                ('leverage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intended_entry', models.FloatField(blank=True, null=True)),
                ('fill_price', models.FloatField(blank=True, null=True)),
                ('order_ids', models.JSONField(default=dict)),
                ('realized_pnl', models.FloatField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('tp', 'Take-profit'), ('sl', 'Stop-loss'), ('invalidated', 'Signal invalidated'), ('manual', 'Manual / kill switch')], default='', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_connection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='auto_trade.brokerconnection')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='signals.signal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='auto_trade__user_id_cf38eb_idx'), models.Index(fields=['status', '-created_at'], name='auto_trade__status_3c8c85_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'signal'), name='uniq_user_signal_execution')],
            },
        ),
    ]
