# Generated by Django 5.1.15 on 2026-06-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeexecution',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeexecution',
            name='sl_moved_to_be',
            field=models.BooleanField(default=False),
        ),
    ]
