# Generated by Django 5.1.15 on 2026-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium (legacy)')], default='premium', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium (legacy)')], default='free', max_length=16),
        ),
    ]
