# Generated by Django 5.1.15 on 2026-06-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_subscription_tier_alter_user_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_link_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
