# Generated by Django 5.1.15 on 2026-06-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_referral_credits_user_referred_by_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_link_token_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
