# Generated by Django 5.1.15 on 2026-06-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_telegram_link_token_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_active',
            field=models.BooleanField(default=True),
        ),
    ]
