# Generated by Django 5.1.15 on 2026-07-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_telegram_active_default_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_promo_code_used',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
