# Generated by Django 5.1.15 on 2026-07-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_pro_promo_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_expiry_notified_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
