# Generated by Django 5.1.15 on 2026-07-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_plan_expiry_notified_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starter_promo_code_used',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
