# Generated by Django 5.1.15 on 2026-07-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_starter_promo_code_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('disputed', 'Disputed (chargeback)'), ('refunded', 'Refunded')], default='active', max_length=16),
        ),
    ]
