# Generated by Django 5.1.15 on 2026-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_withdrawal_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marketing_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
